name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Environment Variables
        run: echo "DATABASE_URL=postgres://username:password@localhost/dbname" >> $GITHUB_ENV

      - name: Start Application
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

      - name: Health Check
        run: |
          sleep 10  # Give the server time to start
          curl --silent --fail http://localhost:8000/health || exit 1
