name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest --maxfail=3 --disable-warnings -q

      - name: Code Coverage
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
          coverage html
          
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-html/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python Code
        run: |
          pip install pylint
          pylint src --max-line-length=120

  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Safety for Security Check
        run: |
          pip install safety
          safety check
